kind: Service
apiVersion: v1
metadata:
  name: qpush-agent
spec:
  type: LoadBalancer
  selector:
    app: qpush-agent
  ports:
  - name: internel
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
