kind: Service
apiVersion: v1
metadata:
  name: push-go-service
spec:
  type: LoadBalancer
  selector:
    app: push-
  ports:
  - name: internel
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
