apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: qpush-agent-deployment
  labels:
    app: qpush-agent
spec:
  selector:
    matchLabels:
      app: qpush-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: qpush-agent
    spec:
      containers:
      - name: qpush-agent
        image: h1.ywopt.com/ywopt.com/qpush:latest
        env:
        - name: CONF
          value: "conf_test.toml"
        - name: EXEC_FILE
          value: "app/client/agent/agent.go queue_push"
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT
          valueFrom:
            secretKeyRef:
              name: micro-audit-secret
              key: JAEGER_AGENT_PORT
        ports:
        - containerPort: 8080
          name: debug-node
        - containerPort: 8081
          name: http-node
        - containerPort: 8082
          name: grpc-node
      imagePullSecrets:
      - name: harbor-secret
