kind: Service
apiVersion: v1
metadata:
  name: qpush-service
spec:
  type: LoadBalancer
  selector:
    app: qpush
  ports:
  - name: externel
    protocol: TCP
    port: 8888
    targetPort: 8888
  - name: externel-http
    protocol: TCP
    port: 8080
    targetPort: 8080  
  - name: internel
    protocol: TCP
    port: 8890
    targetPort: 8890
