apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: qpush-deployment
  labels:
    app: qpush
spec:
  selector:
    matchLabels:
      app: qpush
  replicas: 1
  template:
    metadata:
      labels:
        app: qpush
    spec:
      containers:
      - name: qpush
        image: h1.ywopt.com/ywopt.com/qpush:latest
        env:
        - name: CONF
          value: "conf_test.toml"
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT
          valueFrom:
            secretKeyRef:
              name: micro-audit-secret
              key: JAEGER_AGENT_PORT
        ports:
        - containerPort: 8888
          name: external
        - containerPort: 8890
          name: internal
      imagePullSecrets:
      - name: harbor-secret
